spring.application.name=ease_splitBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/ease_split
spring.datasource.username=ease_split
spring.datasource.password=julius

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
